# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "graylog_vagrant" 
    vb.memory = "4096"
    vb.cpus = 4
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansible/playbook.yml"
  end

end
